### ISSUE TITLE
failed to get the IG from initiator

### ISSUE THREAD

**Issue by tonyfts** [dell/PyU4V#29]
>>> conn.provisioning.get_initiator_group_from_initiator('21000024ff34cefd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/PyU4V/provisioning.py", line 403, in get_initiator_group_from_initiator
    init_details = self.get_initiator(initiator)
  File "/usr/local/lib/python3.4/dist-packages/PyU4V/provisioning.py", line 319, in get_initiator
    resource_name=initiator_id)
  File "/usr/local/lib/python3.4/dist-packages/PyU4V/common.py", line 321, in get_resource
    return self.get_request(target_uri, resource_type, kwargs.get('params'))
  File "/usr/local/lib/python3.4/dist-packages/PyU4V/common.py", line 277, in get_request
    self.check_status_code_success(operation, sc, message)
  File "/usr/local/lib/python3.4/dist-packages/PyU4V/common.py", line 167, in check_status_code_success
    data=exception_message)
PyU4V.utils.exception.VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Error get initiator. The status code received is 500 and the message is {'message': "A problem occurred retrieving the initiator resource: ID 000297800192:21000024ff34cefd does not contain 4 tokens separated by ':'"}.

**Comment by ghost** [comment]
Hi Tony,

You need to ensure that you are passing in the correct Initiator ID format, 000297800192:21000024ff34cefd is incorrect they are in a format such as FA-2D:5:10000000c9768497.

Thanks
Michael

**Comment by tonyfts** [comment]
Yes, the parameter should be 'FA-2D:24:10000000c99a97e2', so following command is OK. 
conn.provisioning.get_initiator_group_from_initiator('FA-2D:24:10000000c99a97e2')

thanks.

**Comment by ghost** [comment]
No problem happy to hear it was a simple solution!
