### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by Gerry-liu** [dell/PyU4V#87]
Hi expert,

   I followed guide to setup PyU4V. then get below issue. Can you help to give some advices? many Thanks.
Used the latest Powermax Unisphere Demo V9.1.0.1 and  the latest PyY4V code.

[root@gerry-centos77 ~]# python
Python 3.7.5 (default, Apr  4 2020, 15:08:30)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyU4V
>>> conn=PyU4V.U4VConn()
/usr/local/python3/lib/python3.7/site-packages/urllib3/connection.py:384: SubjectAltNameWarning: Certificate for 192.168.78.1 has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/urllib3/urllib3/issues/497 for details.)
  SubjectAltNameWarning,
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connection.py", line 386, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connection.py", line 396, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/local/python3/lib/python3.7/ssl.py", line 340, in match_hostname
    raise CertificateError("no appropriate commonName or "
ssl.SSLCertVerificationError: ('no appropriate commonName or subjectAltName fields were found',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.78.1', port=8444): Max retries exceeded with url: /univmax/restapi/version (Caused by SSLError(SSLCertVerificationError('no appropriate commonName or subjectAltName fields were found')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/PyU4V/rest_requests.py", line 104, in rest_request
    timeout=timeout_val)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.78.1', port=8444): Max retries exceeded with url: /univmax/restapi/version (Caused by SSLError(SSLCertVerificationError('no appropriate commonName or subjectAltName fields were found')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.7/site-packages/PyU4V/univmax_conn.py", line 115, in __init__
    self.validate_unisphere()
  File "/usr/local/python3/lib/python3.7/site-packages/PyU4V/univmax_conn.py", line 149, in validate_unisphere
    uni_ver, major_ver = self.common.get_uni_version()
  File "/usr/local/python3/lib/python3.7/site-packages/PyU4V/common.py", line 488, in get_uni_version
    response = self.get_resource(category=VERSION, no_version=True)
  File "/usr/local/python3/lib/python3.7/site-packages/PyU4V/common.py", line 346, in get_resource
    target_uri, resource_type, kwargs.get('params'))
  File "/usr/local/python3/lib/python3.7/site-packages/PyU4V/common.py", line 315, in get_request
    message, sc = self.request(target_uri, GET, params=params)
  File "/usr/local/python3/lib/python3.7/site-packages/PyU4V/rest_requests.py", line 133, in rest_request
    raise r_exc.SSLError(msg)
requests.exceptions.SSLError: The connection to https://192.168.78.1:8444/univmax/restapi has encountered an SSL error. Please check your SSL config or supplied SSL cert in Cinder configuration. SSL Exception message: HTTPSConnectionPool(host='192.168.78.1', port=8444): Max retries exceeded with url: /univmax/restapi/version (Caused by SSLError(SSLCertVerificationError('no appropriate commonName or subjectAltName fields were found')))
>>>

**Comment by Gerry-liu** [comment]
.PyU4V/PyU4V.conf file:
[setup]
; enter the below details - mandatory
;(can be passed as parameters on initialisation also)
username=smc
password=smc
server_ip=192.168.78.1
port=8444
array=000197900049
; remote_array=00012345679
; verify=True
verify=/root/unisphere.pem

the  unisphere.pem file use below command to generate:
openssl s_client -showcerts -connect 192.168.78.1:8444 </dev/null 2>/dev/null|openssl x509 -outform PEM > unisphere.pem

**Comment by rawstorage** [comment]
Gerry, have you tried this with an actual install of Unisphere?, since you are using the demo kit which we don't officially support with PyU4V not sure why you are verifying certificates.  If you set verify to False this error should go away.

**Comment by Gerry-liu** [comment]
got, thanks. I will close this issue.

**Comment by vijayshihan** [comment]
Hi Team, how I can generate certificate for Unisphere server and use it in Dell emc rest api authentication

**Comment by rawstorage** [comment]
you can replace the certificates on the Unipshere server as per the Unisphere documentation, once the Unisphere Server and REST client are using the same trust authorities ssl certs can be used, from PyU4V point of view all you need to do is set verify_certs=True in the config file or connection string..  

Please in  future though open a new issue, this is a closed issue and not related to your question.  Unipshere for PowerMax help and developer.dell.com documentation should also be consulted.
